#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/sbednarek/MARCIN_HOME/Apps/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/sbednarek/MARCIN_HOME/Apps/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/guest/MARCIN_HOME/RobotProject/braitenberg/Things/x86_64/.libs/libnrnmech.so" "$@"
